version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_install:
      - pip install poetry==1.8.2 pyproject_hooks==1.0.0
      - poetry config virtualenvs.create false
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install
mkdocs:
  configuration: mkdocs.yml
