name: tests

on:
  push:
    branches:
      - "**"
    tags:
      - "!**"
  workflow_call:

env:
  POETRY_VERSION: 1.8.2

jobs:
  Tests:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        # TODO: re-enable 3.11
        PYTHON_VERSION: ["3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.PYTHON_VERSION }}

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: ${{env.POETRY_VERSION}}
          installer-parallel: true

      - name: Set up miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          channels: bioconda,conda-forge
          activate-environment: prymer
          environment-file: prymer.yml
          channel-priority: true
          auto-update-conda: true
          auto-activate-base: false
          python-version: ${{ matrix.PYTHON_VERSION }}

      - name: Install the project's dependencies
        shell: bash -el {0}
        run: poetry install

      - name: Test the codebase
        shell: bash -el {0}
        run: poetry run pytest

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.5.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

# Disabling build of docs on dev until we're done with refactoring
#      - name: Test building the documentation
#        shell: bash -el {0}
#        run: poetry run mkdocs build --strict
