name: build wheels

on:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  build-wheels:
    name: Build wheels for ${{ matrix.python }}
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        # TODO: re-enable 3.11
        python: ["3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Set up Python ${{ matrix.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install Linux build prerequisites
        if:   runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -q --no-install-recommends --no-install-suggests libbz2-dev libcurl4-openssl-dev liblzma-dev libssl-dev libdeflate-dev

      - name: Update macOS build prerequisites
        if:   runner.os == 'macOS'
        run: |
          brew unlink xz || true  # Remove brewed liblzma as it is not multiarch

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Build wheels
        run: uv build --wheel -o wheelhouse

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: prymer-wheels-${{ matrix.python }}
          path: ./wheelhouse/prymer*.whl
          if-no-files-found: error
