name: build wheels

on:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  build-wheels:
    name: Build wheels for ${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Set up Python ${{ matrix.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Build wheels
        run: pip wheel -w wheelhouse .

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: prymer-wheels-${{ matrix.python }}
          path: ./wheelhouse/*.whl
          if-no-files-found: error
